services:
  kafka-connect-ui:
    container_name: kafka-connect-ui
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    ports:
      - 3000:3000
    networks:
      - dev_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  dev_network:
    external: true
